import React from 'react';

import { Box, SimpleGrid } from '@chakra-ui/layout';
import { Container } from '@chakra-ui/react';
import Head from 'next/head';

import Card from '../components/Card/Card';
import Footer from '../components/Footer/Footer';
import Hero from '../components/Hero/Hero';
import Navbar from '../components/Navbar/Navbar';
import Testimonials from '../components/Testimonials/Testimonials';

const Home = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <Navbar />
      <Hero />
      <Container maxW="container.xl" mt={[0, -48]}>
        <SimpleGrid columns={[1, 1, 2, 3, 3]}>
          <Box>
            <Card />
          </Box>
          <Box w="100%">
            <Card />
          </Box>
          <Box w="100%">
            <Card />
          </Box>
        </SimpleGrid>
      </Container>
      <Testimonials />
    </main>

    <Footer />
  </div>
);

export default Home;
