import React from 'react'
import Head from 'next/head'
import WithSubnavigation from '../components/Navbar/Navbar'
import Hero from '../components/Hero/Hero'
import { Box, SimpleGrid } from '@chakra-ui/layout'
import Card from '../components/Card/Card'

const Home = () => {

  return (
    <div>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <WithSubnavigation/>
        <Hero/>
        <SimpleGrid columns={[1,1,2,3,4]} spacing={4} p={4}>
          <Box>
            <Card/>
          </Box>
          <Box w="100%">
            <Card/>
          </Box>
          <Box w="100%">
            <Card/>
          </Box>
          <Box w="100%">
            <Card/>
          </Box>
          <Box w="100%">
            <Card/>
          </Box>
        </SimpleGrid>
       
        
      </main>

      <footer >
       
      </footer>
    </div>
  )
}

export default Home